CREATE TABLE products
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    sku VARCHAR(64) NOT NULL,
    description VARCHAR(1000),
    price NUMERIC(19,2) NOT NULL,
    category_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_product_sku UNIQUE (sku),
    CONSTRAINT ck_product_price_non_negative
        CHECK ( price >=0 ),

    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
            REFERENCES categories (id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_product_supplier
        FOREIGN KEY (supplier_id)
            REFERENCES suppliers (id)
            ON DELETE RESTRICT
)